=== kathi1987/clickwatch/core/de.hub.clickwatch.core.test/resources/link_stat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tau">
		<xs:complexType>
			<xs:attribute name="value" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="probes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="probe" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="time" type="xs:decimal" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="probe">
		<xs:complexType>
			<xs:attribute name="size" type="xs:short" use="required"/>
			<xs:attribute name="rate" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="period">
		<xs:complexType>
			<xs:attribute name="value" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="link_info">
		<xs:complexType>
			<xs:attribute name="size" type="xs:short" use="required"/>
			<xs:attribute name="rev" type="xs:byte" use="required"/>
			<xs:attribute name="rate" type="xs:byte" use="required"/>
			<xs:attribute name="fwd" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="link_info" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="to" type="xs:string" use="required"/>
			<xs:attribute name="tau" type="xs:int" use="required"/>
			<xs:attribute name="seq" type="xs:short" use="required"/>
			<xs:attribute name="period" type="xs:short" use="required"/>
			<xs:attribute name="last_rx" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="handlers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="handler" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="elem_name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BRN2LinkStat"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="handler">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="badnodes"/>
				<xs:element ref="entry"/>
				<xs:element ref="period"/>
				<xs:element ref="probes"/>
				<xs:element ref="tau"/>
			</xs:choice>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="bad_version"/>
						<xs:enumeration value="bcast_stats"/>
						<xs:enumeration value="period"/>
						<xs:enumeration value="probes"/>
						<xs:enumeration value="tau"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="entry">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="link" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="time" type="xs:decimal" use="required"/>
			<xs:attribute name="tau" type="xs:int" use="required"/>
			<xs:attribute name="seq" type="xs:short" use="required"/>
			<xs:attribute name="period" type="xs:short" use="required"/>
			<xs:attribute name="from" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="badnodes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="badnode" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="time" type="xs:decimal" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="badnode">
		<xs:complexType>
			<xs:attribute name="version" type="xs:byte" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kathi1987/clickwatch/core/de.hub.clickwatch.core.test/resources/link_stat_runtime.xml
<?xml version="1.0" encoding="UTF-8"?>
<handlers elem_name="BRN2LinkStat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="platform:/plugin/de.hub.clickwatch.core.test/resources/link_stat.xsd">
	<handler name="bcast_stats">
		<entry from="06-0F-B5-97-36-D8" time="1297865583.873778100" seq="616" period="2000" tau="100000">
			<link to="06-0F-B5-97-36-54" seq="616" period="2000" tau="100000" last_rx="0.569037100">
				<link_info size="200" rate="2" fwd="94" rev="92"/>
				<link_info size="500" rate="12" fwd="54" rev="42"/>
			</link>
			<link to="06-0F-B5-97-37-FC" seq="617" period="2000" tau="100000" last_rx="0.974657100">
				<link_info size="500" rate="2" fwd="98" rev="100"/>
				<link_info size="400" rate="4" fwd="78" rev="90"/>
			</link>
		</entry>
	</handler>
	<handler name="bad_version">
		<badnodes id="06-11-6B-60-48-A5" time="1297866403.933551985">
			<badnode id="06-0F-B5-97-36-D8" version="101"/>
			<badnode id="06-0F-B5-97-36-DE" version="102"/>
		</badnodes>
	</handler>
	<handler name="tau">
		<tau value="100000"/>
	</handler>
	<handler name="period">
		<period value="2000"/>
	</handler>
	<handler name="probes">
		<probes id="06-11-6B-60-48-A5" time="1297866479.271011241">
			<probe rate="2" size="500"/>
			<probe rate="4" size="400"/>
			<probe rate="12" size="500"/>
		</probes>
	</handler>
</handlers>
